//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable_room_facility
    {
        public string Building_ID { get; set; }
        public string Room_ID { get; set; }
        public int Facility_ID { get; set; }
        public int Quantity { get; set; }
    }
}
