//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable_round
    {
        public int Current_Year { get; set; }
        public byte Current_Semester { get; set; }
        public byte Current_Round { get; set; }
        public byte Current_Round_Status { get; set; }
        public byte Adhoc_Status { get; set; }
    }
}
