//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable_building
    {
        public timetable_building()
        {
            this.timetable_request_room_allocation = new HashSet<timetable_request_room_allocation>();
        }
    
        public string Building_ID { get; set; }
        public string Building_Name { get; set; }
        public int Park_ID { get; set; }
    
        public virtual timetable_park timetable_park { internal get; set; }
        public virtual ICollection<timetable_request_room_allocation> timetable_request_room_allocation { internal get; set; }
    }
}
