//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable_department
    {
        public int Department_ID { get; set; }
        public string Department_Code { get; set; }
        public string Department_Name { get; set; }
        public short Current_Round { get; set; }
        public string Password { get; set; }
        public string Password_Salt { get; set; }
    
        public virtual timetable_round timetable_round { get; set; }
    }
}
