//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProjects.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class timetable_module
    {
        [Required]
        public string Department_Code { get; set; }
        [Required]
        public string Part_Code { get; set; }
        [Required]
        public string Module_Code { get; set; }
        [Required]
        public string Module_Title { get; set; }
        [Required]
        public bool Active { get; set; }
    }
}
